### ISSUE TITLE
Open TW file from the command line

### ISSUE THREAD

**Issue by JohnHind** [Jermolene/TiddlyDesktop#16] opened 2014-02-18 20:10 UTC
Would it be possible to support specifying the TiddlyWiKi file as a command line parameter to nw.exe? I would like to be able to make shortcuts that open specific files directly.

Also, I found it is possible to open a file by dropping it onto the TiddlyDesktop window, but files opened in this way cannot be saved and do not appear subsequently in the TiddlyDesktop list (I am guessing this is an "accidental feature"!).

**Comment by Jermolene** [comment] 2015-12-06 08:26
Dupe of #69

**Closed by Jermolene** 2015-12-06 08:26 UTC
Labels: enhancement
