### ISSUE TITLE
allow searches in the visible page

### ISSUE THREAD

**Issue by ittayd** [Jermolene/TiddlyDesktop#82] opened 2015-12-10 07:38 UTC
Sometimes I have a tiddler or few open and I want to search within those only. The browser can do that, with incremental search, but this is not available in tiddlydesktop

**Comment by Jermolene** [comment] 2015-12-10 08:24
Hi @ittayd I think this is a duplicate of #21.

**Closed by Jermolene** 2015-12-10 08:24 UTC
