### ISSUE TITLE
Saving a wiki suddenly started prompting me with a Save As window

### ISSUE THREAD

**Issue by braykov** [Jermolene/TiddlyDesktop#51] opened 2015-01-15 12:54 UTC
The first few saves were OK. I was getting the yellow message with wiki saved.
But after some saves, saving it opened a Save As window and a Cancel cleared the "unsaved" status of the save icon, but my wiki was not saved.
Subsequent clicks also opened the Save As window.

Version 0.0.4 on Windows 7 64bit

**Comment by Jermolene** [comment] 2015-02-07 12:10
Hi @braykov have you been able to reproduce this problem?

**Comment by braykov** [comment] 2015-02-07 16:51
@Jermolene I haven't played with it under Windows anymore as I couldn't get nw to start at all. It started as a process, but nothing showed on the screen.

**Comment by Jermolene** [comment] 2015-12-06 08:24
Hi @braykov I'll close this on the basis that we can't reproduce it.

**Closed by Jermolene** 2015-12-06 08:24 UTC
Labels: bug
