### ISSUE TITLE
Mac App - nwjs crashes on exit

### ISSUE THREAD

**Issue by comdotdom** [Jermolene/TiddlyDesktop#131] opened 2018-01-08 12:49 UTC
![screenshot 2018-01-08 12 45 14](https://user-images.githubusercontent.com/5439759/34671320-06e206fc-f472-11e7-95f4-25ac136eb31f.png)

Process:               nwjs [14108]
Path:                  /Applications/TiddlyWiki.app/Contents/MacOS/nwjs
Identifier:            com.tiddlywiki
Version:               0.0.10 (10)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           nwjs [14108]
User ID:               501

Date/Time:             2018-01-08 12:47:17.939 +0000
OS Version:            Mac OS X 10.13.2 (17C88)
Report Version:        12

**Comment by Jermolene** [comment] 2018-01-08 12:52
Thanks @comdotdom I think this is a dupe of #112?

**Comment by comdotdom** [comment] 2018-01-08 12:54
You’re quite right - so sorry (only extra info - I am on High Sierra, user from 112 was on Sierra.)

**Comment by Jermolene** [comment] 2018-01-08 12:56
Hi @comdotdom no worries, its pretty hard to find things in the issue list :)

**Closed by Jermolene** 2018-01-08 12:56 UTC
