### ISSUE TITLE
Support for TW Classic in TiddlyDesktop 0.0.9

### ISSUE THREAD

**Issue by jockster74** [Jermolene/TiddlyDesktop#105] opened 2017-10-25 06:00 UTC
I have used mGTD, based on Tiddlywiki Classic, with TiddlyDesktop 0.0.8 for a long time, without any major problems. I downloaded version 0.0.9 and ran into the problem of not being able to save my edits. When I click Save, the error message I get is:

> It’s not possible to save changes. Possible reasons include:
> - your browser doesn’t support saving (Firefox, Internet Explorer: Safari and
> Opera all work if properly configured)
> - the pathname to your TiddlyWiki file contains illegal characters
> - the TiddlyWiki HTML file has been moved or renamed

I believe this is related to [Issue #3](https://github.com/Jermolene/TiddlyDesktop/issues/3). From that issue, I got the impression that Tiddlywiki Classic is supported (and it worked fine in 0.0.8).

**Comment by snowshome** [comment] 2017-11-18 13:18
@jockster74 have you tried moving back to 0.0.8?  I am facing the challenge of moving from FireFox to tiddlydesktop to continue using mGTD.

**Comment by jockster74** [comment] 2017-11-28 20:50
Yeah, I still use mGTD daily on TiddlyDesktop 0.0.8. It is very stable.

**Comment by snowshome** [comment] 2017-11-29 01:54
I see.  Thanks.  I've got my files sync'd with Resilio across devices, and lots of mGTD data I don't want to abandon.  I set up 0.0.8 on one machine - so it is nice to have a fall back option.

**Comment by simonpa71** [comment] 2017-12-11 14:42
I am running into the same issue under Windows 10. 
I tried running nw.exe as Administrator, but no difference.

**Comment by Jermolene** [comment] 2017-12-12 16:01
@jockster74 apologies for the delay. What operating system are you using?

On Mac OS X 10.12.6 I'm able to save changes with TiddlyWiki Classic 2.8.1 in TiddlyDesktop v0.0.9. Saving works fine; however there is a different problem whereby clicking a button yields the error below:

<img width="688" alt="there is no application set to open" src="https://user-images.githubusercontent.com/174761/33894347-a85c56b8-df55-11e7-8093-f5803889d6bc.png">

**Comment by snowshome** [comment] 2017-12-12 20:37
Windows 10  pro is what I am using,   

Best Regards, -- David

**Comment by hauptmech** [comment] 2017-12-17 04:08
Also having issues saving classic tiddlywiki under 0.0.9 windows.  Now using 0.0.8 successfully.

**Comment by jockster74** [comment] 2017-12-22 11:32
@Jermolene I am using Windows 7 Enterprise SP1.

**Comment by Jermolene** [comment] 2018-01-08 11:04
These problems should be fixed with the new v0.0.10:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.10

Please let me know how you get on.

**Comment by jockster74** [comment] 2018-01-10 12:39
Thanks. I gave version 0.0.10 a try and am afraid it gives me the same error message as originally reported.

Just to make sure I had not fiddled with the file in any way, I downloaded a fresh copy of mGSD (http://mgsd.tiddlyspot.com/#Download) and opened that in v. 0,0.10. The results are the same - I am not able to save.

**Comment by Jermolene** [comment] 2018-01-10 12:50
Thanks @jockster74 

Does v0.0.10 or the new v0.0.11 work if you try to edit a plain empty wiki downloaded from https://classic.tiddlywiki.com/empty.html?

**Comment by snowshome** [comment] 2018-01-10 15:32
@Jermolene  Thanks for tackling this!  

I've downloaded and installed 64bit v0.0.10 and v0.0.11 onto my Win10 pro Ms Surface 4
plain empty wiki classic - add, edit, save toddlers. ok on both.
mGSD - neither 10 or 11 allow adds or edits to be saved.    

Best Regards, -- David

**Comment by Jermolene** [comment] 2018-01-10 16:30
Thanks @snowshome. What version of TiddlyWiki is your mGSD wiki? (You can use the `<<version>>` macro to find out, or just "view source" and look for the version number at the top of the file).

**Comment by zielot** [comment] 2018-01-10 17:06
@Jermolene - 
I just downloaded TW11 and hoped that it would address the issue I had with v0.0.9 but alas, it did not. Using the version macro my large, legacy wiki tells me that I am using version 2.6.1.

Regards, Justin

BTW - Thanks for keeping us legacy users in mind with your TW development work. I really appreciate all of the work you have put in over the years to start and maintain this project. My oldest entry for the wiki in question is from 10 years ago!

**Comment by snowshome** [comment] 2018-01-10 17:25
@Jermolene -  my mgsd version macro shows 2.6.5.  I tried a new vanilla mgsd (version 2.6.5) also - edits/saves work in v0.0.8, but not in v0.0.11.    Ditto on the Thanks!  (Perhaps you remember a call we had maybe 10 years ago with Greg Wolff at Ricoh on use cases I had in TW?)

**Comment by Jermolene** [comment] 2018-01-11 09:06
Hi @snowshome - indeed I remember the Fair Trade project with Greg, wonderful to learn that you're still using TW. I'll run some tests on TWC v2.6.5

Hi @zielot - thanks, I'll run some tests with TWC v2.6.1 as well

**Comment by dgerod** [comment] 2018-01-26 09:55
@Jermolene, I have same save problem with TWC 2.6.2 and TiddyDesktop 0.0.11 in Ubuntu 16.04.

**Comment by clayrat** [comment] 2018-02-01 18:07
Same issue on TWC 2.6.2 and TiddlyDesktop 0.0.11

**Comment by Jermolene** [comment] 2018-02-01 19:38
Hi everybody please could you try [release v0.0.12](https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.12)? I believe that this issue is fixed.

**Comment by clayrat** [comment] 2018-02-02 12:12
Sorry, but it seems the issue is still there for me.

**Comment by snowshome** [comment] 2018-02-02 20:13
I tested 3 files in 0.0.12

my TWC 2.6.2 based mGSD file      - result: NG  doesn't allow saving of tidder edits
empty TWC 2.6.2 based mGSD file - results NG doesn't allow saving of tidder edits
empty wiki 5.1.15                          - results: OK  allows saving of tiddler edits

**Comment by dgerod** [comment] 2018-02-03 07:26
I have also tried with my customized version of TWC 2.6.2 in Ubuntu 16.04 and it does not work.

**Comment by Jermolene** [comment] 2018-02-08 19:10
This should be fixed in the latest v0.0.13:

https://github.com/Jermolene/TiddlyDesktop/releases/tag/v0.0.13

**Comment by dgerod** [comment] 2018-02-09 07:05
Yes! it works in Ubuntu 16.04. And I will check in Windows 7 during this weekend.

Thanks.

**Comment by Jermolene** [comment] 2018-02-09 08:52
That's great @dgerod thanks for letting me know

**Comment by Jeff314116** [comment] 2018-02-09 09:40
Hi, it's extremely strange... With 0.0.13, under W7, when I open Classic TW it also open it in my default browser!

**Comment by snowshome** [comment] 2018-02-09 13:18
I tested 3 files in 0.0.13  Success!!

my TWC 2.6.2 based mGSD file - result: OK, allows saving of tiddler edits
empty TWC 2.6.2 based mGSD file - result: OK, allows saving of tiddler edits
empty wiki 5.1.15 - result: OK, allows saving of tiddler edits

Thanks so much @Jermolene .    -David.

**Comment by dgerod** [comment] 2018-02-11 05:40
I tried in Windows 7 and it works. 

However, I had to download the NWJS for Windows from their web and replaced ones coming with TiddlyDesktop. When I used onces in TiddlyDesktop, Windows raised an error saying that these files don't work in this OS. And I tried 32 and 64 versions of TiddlyDesktop with same results. After this file replacement all works.

**Comment by Jermolene** [comment] 2018-02-12 20:12
@snowshome - thanks!

@Jeff314116 - I can't duplicate that with my Windows 10 virtual machine; I'll try under Windows 7 when I get a chance. Do you get this behaviour for all TWC wikis? What version(s) are you using?

**Comment by Jeff314116** [comment] 2018-02-13 09:48
@Jermolene I have the problem with dGSD V1.6 (with my current file and with an empty file). No problem with TW5 and with classic TW 2.8.1.

**Comment by Jermolene** [comment] 2018-02-13 09:49
Hi @Jeff314116 that's very helpful; could you link to a copy of dGSD that has the problem so that I can test?

**Comment by Jeff314116** [comment] 2018-02-13 09:53
Hi @Jermolene 
http://cardo.wiki/dGSD/

**Comment by jockster74** [comment] 2018-03-01 07:04
@Jermolene  Very happy to report that using mGSD with release 13 of Tiddlywiki desktop works like a charm! Please close this issue. :+1:  Thanks for all the work, Jeremy.

**Comment by Jermolene** [comment] 2018-03-01 07:53
Thanks @jockster74 that's great to hear!

**Closed by Jermolene** 2018-03-01 07:53 UTC
